version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        HTTP_SERVER_PORT: ${HTTP_BACKEND_SERVER_PORT}
        APP_NAME: xyz-home-task-backend
    ports:
      - ${HTTP_BACKEND_SERVER_PORT}:${HTTP_BACKEND_SERVER_PORT}
    environment:
      - HOST=0.0.0.0
      - HTTP_SERVER_PORT=${HTTP_BACKEND_SERVER_PORT}
      - LOG_LEVEL=${BACKEND_LOG_LEVEL}
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        SERVER_PORT: ${HTTP_FROTNEND_SERVER_PORT}
        API_PORT: ${HTTP_BACKEND_SERVER_PORT}
        APP_NAME: xyz-home-task-frontend
    ports:
      - ${HTTP_FROTNEND_SERVER_PORT}:80
    depends_on:
      - backend
  doc-server:
    build:
      context: ./doc-server
      dockerfile: Dockerfile
      args:
        APP_NAME: xyz-home-task-doc-server
    ports:
      - ${HTTP_DOC_SERVER_PORT}:80
