run:
  concurrency: 2
  timeout: 10m
linters:
  enable-all: true
  disable:
    - depguard
    - gci
    - zerologlint
    - execinquery
    - exportloopref
    - gomnd
linters-settings:
  varnamelen:
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *foo.Bar
      - e error
      - i int
      - const C
      - T any
      - m map[string]int
      - w http.ResponseWriter
      - r *http.Request
  lll:
    line-length: 80
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
  exhaustruct:
    exclude:
      - '.+/telebot\..+$'
