openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: This is a documentation for test task.
servers:
  - url: /api/v1
tags:
  - name: books
    description: Everything related to books
paths:
  /books:
    get:
      operationId: getBooks
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: Filter query
      summary: Get all books
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksListResponse'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "408":
          description: Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Description of the error
          example: Internal server error occurred
      required:
        - message
    BookBase:
      type: object
      properties:
        id:
          type: string
          description: Unique ID
          example: dIewflkjW
        title:
          type: string
          description: Title of the book
          example: Vim for everyone
        description:
          type: string
          description: Description of the book
          example: Blah blah blah and so on
        pages:
          type: integer
          description: Pages in the book
          example: 245
        price:
          type: number
          format: float
          description: Price of the book
          example: 30
        currency:
          type: string
          description: Currency of price
          exampe: USD
        thumbnail:
          type: string
          description: Thumbnail URL
          exampe: https://some.thumbnail.com/id324234
        revision:
          type: integer
          description: Revision
          exampe: 4
      required:
        - id
        - title
        - description
        - pages
        - price
        - currency
        - thumbnail
    BooksListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/BookBase'
      required:
        - items
